// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp2G6-4WEMIjbfD6_ub5OG7Hf1HFz62Do',
    appId: '1:169249306864:web:d76b7bf0e26f6d83fdaa35',
    messagingSenderId: '169249306864',
    projectId: 'to-do-bb94f',
    authDomain: 'to-do-bb94f.firebaseapp.com',
    storageBucket: 'to-do-bb94f.firebasestorage.app',
    measurementId: 'G-KYNL5TXZDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZ0QWG4COhPb6WHOZrotIA2G1zot5IuM',
    appId: '1:169249306864:android:1d5d3864ff2b1615fdaa35',
    messagingSenderId: '169249306864',
    projectId: 'to-do-bb94f',
    storageBucket: 'to-do-bb94f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPE5g17nb1nQwU2XBp-avMQHciLw3JBQc',
    appId: '1:169249306864:ios:21c066218caa965dfdaa35',
    messagingSenderId: '169249306864',
    projectId: 'to-do-bb94f',
    storageBucket: 'to-do-bb94f.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPE5g17nb1nQwU2XBp-avMQHciLw3JBQc',
    appId: '1:169249306864:ios:21c066218caa965dfdaa35',
    messagingSenderId: '169249306864',
    projectId: 'to-do-bb94f',
    storageBucket: 'to-do-bb94f.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp2G6-4WEMIjbfD6_ub5OG7Hf1HFz62Do',
    appId: '1:169249306864:web:19be900866146376fdaa35',
    messagingSenderId: '169249306864',
    projectId: 'to-do-bb94f',
    authDomain: 'to-do-bb94f.firebaseapp.com',
    storageBucket: 'to-do-bb94f.firebasestorage.app',
    measurementId: 'G-F5QSN7KE8J',
  );
}
